# Generated by Django 5.0.3 on 2024-03-27 14:10

import django.db.models.deletion
import froala_editor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('content_text', models.TextField(blank=True, default=None, null=True, verbose_name='Статья')),
                ('content_picture', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Картинка')),
                ('content_audio', froala_editor.fields.FroalaField(blank=True, default=None, null=True, verbose_name='Аудио')),
                ('content_video', froala_editor.fields.FroalaField(blank=True, default=None, null=True, verbose_name='Видео')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('publication_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус публикации')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
