# Generated by Django 5.0.4 on 2024-04-08 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('surname_ru', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('surname_en', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('surname_fr', models.CharField(max_length=100, null=True, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('brand_name', models.CharField(max_length=100, verbose_name='Бренд')),
                ('brand_name_ru', models.CharField(max_length=100, null=True, verbose_name='Бренд')),
                ('brand_name_en', models.CharField(max_length=100, null=True, verbose_name='Бренд')),
                ('brand_name_fr', models.CharField(max_length=100, null=True, verbose_name='Бренд')),
                ('biography', models.TextField(blank=True, default=None, null=True, verbose_name='Биография')),
                ('biography_ru', models.TextField(blank=True, default=None, null=True, verbose_name='Биография')),
                ('biography_en', models.TextField(blank=True, default=None, null=True, verbose_name='Биография')),
                ('biography_fr', models.TextField(blank=True, default=None, null=True, verbose_name='Биография')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения записи')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='CategoryProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('name_ru', models.CharField(max_length=100, null=True, verbose_name='Название проекта')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='Название проекта')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_fr', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тема обращения')),
                ('name_ru', models.CharField(max_length=30, null=True, verbose_name='Тема обращения')),
                ('name_en', models.CharField(max_length=30, null=True, verbose_name='Тема обращения')),
                ('name_fr', models.CharField(max_length=30, null=True, verbose_name='Тема обращения')),
            ],
            options={
                'verbose_name': 'Тема обращения обратной связи',
                'verbose_name_plural': 'Темы обращений обратной связи',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=80, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=80, null=True, verbose_name='Заголовок')),
                ('title_fr', models.CharField(max_length=80, null=True, verbose_name='Заголовок')),
                ('content_text', models.TextField(blank=True, default=None, null=True, verbose_name='Статья')),
                ('content_text_ru', models.TextField(blank=True, default=None, null=True, verbose_name='Статья')),
                ('content_text_en', models.TextField(blank=True, default=None, null=True, verbose_name='Статья')),
                ('content_text_fr', models.TextField(blank=True, default=None, null=True, verbose_name='Статья')),
                ('content_picture', models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('content', models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Аудио/Видео')),
                ('content_ru', models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Аудио/Видео')),
                ('content_en', models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Аудио/Видео')),
                ('content_fr', models.FileField(blank=True, default=None, null=True, upload_to='files/%Y/%m/%d/', verbose_name='Аудио/Видео')),
                ('publication_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('publication_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_published', models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], verbose_name='Статус публикации')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.author', verbose_name='Автор')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.categoryproject', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления записи')),
                ('theme', models.ForeignKey(default='no subject', on_delete=django.db.models.deletion.CASCADE, to='gallery.themes', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
    ]
