# Generated by Django 5.0.3 on 2024-03-28 08:15

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='content_picture',
            field=froala_editor.fields.FroalaField(blank=True, default=None, null=True, verbose_name='Картинка'),
        ),
    ]
