# Generated by Django 5.0.3 on 2024-04-24 11:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='project',
        ),
        migrations.AlterModelOptions(
            name='themes',
            options={'verbose_name': 'Тема обращения обратной связи', 'verbose_name_plural': 'Темы обращений обратной связи'},
        ),
        migrations.AddField(
            model_name='author',
            name='patronymic_en',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='author',
            name='patronymic_fr',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='author',
            name='patronymic_ru',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='theme',
            field=models.ForeignKey(default='no subject', on_delete=django.db.models.deletion.CASCADE, to='gallery.themes', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='content_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус публикации'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=80, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=80, null=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='themes',
            name='name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Тема обращения'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название проекта')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Название проекта')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Название проекта')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='Название проекта')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5, message='Минимум 5 символов'), django.core.validators.MaxLengthValidator(100, message='Максимум 100 символов')], verbose_name='Slug')),
                ('description', models.CharField(max_length=50, verbose_name='Слоган')),
                ('description_ru', models.CharField(max_length=50, null=True, verbose_name='Слоган')),
                ('description_en', models.CharField(max_length=50, null=True, verbose_name='Слоган')),
                ('description_fr', models.CharField(max_length=50, null=True, verbose_name='Слоган')),
                ('image_project', models.ImageField(blank=True, default=None, null=True, upload_to='photos_project/%Y/%m/%d/', verbose_name='Титульное изображение')),
                ('title_block_description', models.CharField(max_length=100, verbose_name='Заголовок блока описания')),
                ('title_block_description_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок блока описания')),
                ('title_block_description_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок блока описания')),
                ('title_block_description_fr', models.CharField(max_length=100, null=True, verbose_name='Заголовок блока описания')),
                ('block_description_one', models.CharField(max_length=255, verbose_name='Описание блока No1')),
                ('block_description_one_ru', models.CharField(max_length=255, null=True, verbose_name='Описание блока No1')),
                ('block_description_one_en', models.CharField(max_length=255, null=True, verbose_name='Описание блока No1')),
                ('block_description_one_fr', models.CharField(max_length=255, null=True, verbose_name='Описание блока No1')),
                ('image_block_one', models.ImageField(blank=True, default=None, null=True, upload_to='photos_project/block1/%Y/%m/%d/', verbose_name='Изображение блока No1')),
                ('block_description_two', models.CharField(max_length=255, verbose_name='Описание блока No2')),
                ('block_description_two_ru', models.CharField(max_length=255, null=True, verbose_name='Описание блока No2')),
                ('block_description_two_en', models.CharField(max_length=255, null=True, verbose_name='Описание блока No2')),
                ('block_description_two_fr', models.CharField(max_length=255, null=True, verbose_name='Описание блока No2')),
                ('image_block_two', models.ImageField(blank=True, default=None, null=True, upload_to='photos_project/block2/%Y/%m/%d/', verbose_name='Изображение блока No2')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления записи')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения записи')),
                ('implementation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Реализация')),
                ('implementation_en', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Реализация')),
                ('implementation_fr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Реализация')),
                ('implementation_ru', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery', verbose_name='Реализация')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.DeleteModel(
            name='CategoryProject',
        ),
    ]
