# Generated by Django 5.0.3 on 2024-03-28 09:16

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_content_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='content_text',
            field=froala_editor.fields.FroalaField(blank=True, default=None, null=True, verbose_name='Статья'),
        ),
    ]
