# Generated by Django 5.0.3 on 2024-04-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_gallery_project_alter_themes_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Что мы умеем?')),
                ('name_ru', models.CharField(max_length=50, null=True, verbose_name='Что мы умеем?')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Что мы умеем?')),
                ('name_fr', models.CharField(max_length=50, null=True, verbose_name='Что мы умеем?')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='photos_what_block/', verbose_name='Изображение скилла')),
                ('title', models.CharField(max_length=50, verbose_name='Название скилла')),
                ('title_ru', models.CharField(max_length=50, null=True, verbose_name='Название скилла')),
                ('title_en', models.CharField(max_length=50, null=True, verbose_name='Название скилла')),
                ('title_fr', models.CharField(max_length=50, null=True, verbose_name='Название скилла')),
                ('text', models.CharField(max_length=255, verbose_name='Описание скилла')),
                ('text_ru', models.CharField(max_length=255, null=True, verbose_name='Описание скилла')),
                ('text_en', models.CharField(max_length=255, null=True, verbose_name='Описание скилла')),
                ('text_fr', models.CharField(max_length=255, null=True, verbose_name='Описание скилла')),
            ],
            options={
                'verbose_name': 'Что мы умеем?',
                'verbose_name_plural': 'Что мы умеем?',
            },
        ),
        migrations.RemoveField(
            model_name='project',
            name='implementation_en',
        ),
        migrations.RemoveField(
            model_name='project',
            name='implementation_fr',
        ),
        migrations.RemoveField(
            model_name='project',
            name='implementation_ru',
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_one',
            field=models.TextField(max_length=500, verbose_name='Описание блока No1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_one_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание блока No1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_one_fr',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание блока No1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_one_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание блока No1'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_two',
            field=models.TextField(max_length=500, verbose_name='Описание блока No2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_two_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание блока No2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_two_fr',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание блока No2'),
        ),
        migrations.AlterField(
            model_name='project',
            name='block_description_two_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Описание блока No2'),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_text', models.CharField(max_length=50, verbose_name='Название логотипа')),
                ('logo_text_ru', models.CharField(max_length=50, null=True, verbose_name='Название логотипа')),
                ('logo_text_en', models.CharField(max_length=50, null=True, verbose_name='Название логотипа')),
                ('logo_text_fr', models.CharField(max_length=50, null=True, verbose_name='Название логотипа')),
                ('logo_header', models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера')),
                ('logo_header_ru', models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера')),
                ('logo_header_en', models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера')),
                ('logo_header_fr', models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера')),
                ('about_us', models.CharField(max_length=10, verbose_name='О нас')),
                ('about_us_ru', models.CharField(max_length=10, null=True, verbose_name='О нас')),
                ('about_us_en', models.CharField(max_length=10, null=True, verbose_name='О нас')),
                ('about_us_fr', models.CharField(max_length=10, null=True, verbose_name='О нас')),
                ('about_us_title', models.CharField(max_length=50, verbose_name='Заголовок раздела')),
                ('about_us_title_ru', models.CharField(max_length=50, null=True, verbose_name='Заголовок раздела')),
                ('about_us_title_en', models.CharField(max_length=50, null=True, verbose_name='Заголовок раздела')),
                ('about_us_title_fr', models.CharField(max_length=50, null=True, verbose_name='Заголовок раздела')),
                ('about_us_text', models.TextField(max_length=500, verbose_name='Текст раздела')),
                ('about_us_text_ru', models.TextField(max_length=500, null=True, verbose_name='Текст раздела')),
                ('about_us_text_en', models.TextField(max_length=500, null=True, verbose_name='Текст раздела')),
                ('about_us_text_fr', models.TextField(max_length=500, null=True, verbose_name='Текст раздела')),
                ('logo_footer', models.ImageField(blank=True, default=None, null=True, upload_to='logo_footer/', verbose_name='Логотип футера')),
                ('logo_footer_ru', models.ImageField(blank=True, default=None, null=True, upload_to='logo_footer/', verbose_name='Логотип футера')),
                ('logo_footer_en', models.ImageField(blank=True, default=None, null=True, upload_to='logo_footer/', verbose_name='Логотип футера')),
                ('logo_footer_fr', models.ImageField(blank=True, default=None, null=True, upload_to='logo_footer/', verbose_name='Логотип футера')),
                ('projects', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.project', verbose_name='Проекты')),
                ('projects_en', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.project', verbose_name='Проекты')),
                ('projects_fr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.project', verbose_name='Проекты')),
                ('projects_ru', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.project', verbose_name='Проекты')),
                ('team', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.author', verbose_name='Команда')),
                ('team_en', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.author', verbose_name='Команда')),
                ('team_fr', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.author', verbose_name='Команда')),
                ('team_ru', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallery.author', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Основная страница',
                'verbose_name_plural': 'Основная страница',
            },
        ),
    ]
