# Generated by Django 5.0.3 on 2024-04-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_author_patronymic_remove_author_patronymic_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title_block_description',
            field=models.CharField(max_length=150, verbose_name='Заголовок блока описания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_block_description_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок блока описания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_block_description_fr',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок блока описания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_block_description_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Заголовок блока описания'),
        ),
    ]
