# Generated by Django 5.0.3 on 2024-04-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_project_title_block_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='author',
            name='surname_en',
        ),
        migrations.RemoveField(
            model_name='author',
            name='surname_fr',
        ),
        migrations.RemoveField(
            model_name='author',
            name='surname_ru',
        ),
        migrations.RemoveField(
            model_name='whatblock',
            name='name',
        ),
        migrations.RemoveField(
            model_name='whatblock',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='whatblock',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='whatblock',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя и фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя и фамилия'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='implementation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='what_block',
        ),
        migrations.AddField(
            model_name='project',
            name='implementation',
            field=models.ManyToManyField(to='gallery.gallery', verbose_name='Галереи'),
        ),
        migrations.AddField(
            model_name='project',
            name='what_block',
            field=models.ManyToManyField(related_name='what_block', to='gallery.whatblock', verbose_name='Наши скиллы'),
        ),
    ]
