# Generated by Django 4.2.4 on 2024-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_remove_author_surname_remove_author_surname_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingpage',
            name='projects_en',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='projects_fr',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='projects_ru',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='team_en',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='team_fr',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='team_ru',
        ),
        migrations.AddField(
            model_name='author',
            name='photo_en',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_fr',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo_ru',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_header',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_header_en',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_header_fr',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера'),
        ),
        migrations.AddField(
            model_name='project',
            name='logo_header_ru',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logo_landing/', verbose_name='Логотип хедера'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us',
            field=models.CharField(max_length=50, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_en',
            field=models.CharField(max_length=50, null=True, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_fr',
            field=models.CharField(max_length=50, null=True, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='О нас'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_title',
            field=models.CharField(max_length=100, verbose_name='Заголовок раздела'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок раздела'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_title_fr',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок раздела'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='about_us_title_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Заголовок раздела'),
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='landingpage',
            name='team',
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation',
            field=models.ManyToManyField(related_name='implementation', to='gallery.gallery', verbose_name='Галереи'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_en',
            field=models.TextField(max_length=50, null=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_fr',
            field=models.TextField(max_length=50, null=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_ru',
            field=models.TextField(max_length=50, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='gallery.project', verbose_name='Проекты'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='team',
            field=models.ManyToManyField(related_name='team', to='gallery.author', verbose_name='Команда'),
        ),
    ]
